stages:
  - test

testthat:
  stage: test
  image: rocker/r-ver:latest  # Use an R-based Docker image
  script:
    - apt-get update && apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    - R -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
    - R -e 'devtools::install_deps(dependencies = TRUE)'
    - R -e 'devtools::test()'
  only:
    - merge_requests

